apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- configmap.yaml

patches:
- target:
    kind: Service
    name: guestbook
  patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30084
