apiVersion: v1
kind: ConfigMap
metadata:
  name: guestbook-content
data:
  index.html: |-
    <!DOCTYPE html>
    <html>
    <head>
    <title>dev</title>
    </head>
    <body>

    <h1>dev</h1>

    </body>
    </html>
