apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- configmap.yaml

patches:
- patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30081
  target:
    kind: Service
    name: guestbook
images:
- name: ghcr.io/krancovia/guestbook
  newTag: v0.1.0
